---
name: Getopt-AsDocumented
version: v0.0.1
author:
  - 'Eric Wilhelm @ <ewilhelm at cpan dot org>'
abstract: declare options as pod documentation
license: perl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Getopt-AsDocumented
  homepage: http://scratchcomputing.com/
  license: http://dev.perl.org/licenses/
  repository: http://svn.scratchcomputing.com/Getopt-AsDocumented/trunk
requires:
  Getopt::Base: 0
  Pod::Parser: 0
  YAML: 0
build_requires:
  Module::Build: 0.26
  Test::More: 0
provides:
  Getopt::AsDocumented:
    file: lib/Getopt/AsDocumented.pm
    version: v0.0.1
  Getopt::AsDocumented::PodParser:
    file: lib/Getopt/AsDocumented.pm
generated_by: Module::Build version 0.3103
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
